// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ActionAcceptNewTaskMyNameActionTaskNewPost implements action_accept_new_task_my__name__action_task_new_post operation.
//
// Accepting a new task.
//
// POST /my/{name}/action/task/new
func (UnimplementedHandler) ActionAcceptNewTaskMyNameActionTaskNewPost(ctx context.Context, params ActionAcceptNewTaskMyNameActionTaskNewPostParams) (r ActionAcceptNewTaskMyNameActionTaskNewPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionCompleteTaskMyNameActionTaskCompletePost implements action_complete_task_my__name__action_task_complete_post operation.
//
// Complete a task.
//
// POST /my/{name}/action/task/complete
func (UnimplementedHandler) ActionCompleteTaskMyNameActionTaskCompletePost(ctx context.Context, params ActionCompleteTaskMyNameActionTaskCompletePostParams) (r ActionCompleteTaskMyNameActionTaskCompletePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionCraftingMyNameActionCraftingPost implements action_crafting_my__name__action_crafting_post operation.
//
// Crafting an item. The character must be on a map with a workshop.
//
// POST /my/{name}/action/crafting
func (UnimplementedHandler) ActionCraftingMyNameActionCraftingPost(ctx context.Context, req *CraftingSchema, params ActionCraftingMyNameActionCraftingPostParams) (r ActionCraftingMyNameActionCraftingPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionDeleteItemMyNameActionDeletePost implements action_delete_item_my__name__action_delete_post operation.
//
// Delete an item from your character's inventory.
//
// POST /my/{name}/action/delete
func (UnimplementedHandler) ActionDeleteItemMyNameActionDeletePost(ctx context.Context, req *SimpleItemSchema, params ActionDeleteItemMyNameActionDeletePostParams) (r ActionDeleteItemMyNameActionDeletePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionDepositBankGoldMyNameActionBankDepositGoldPost implements action_deposit_bank_gold_my__name__action_bank_deposit_gold_post operation.
//
// Deposit golds in a bank on the character's map.
//
// POST /my/{name}/action/bank/deposit/gold
func (UnimplementedHandler) ActionDepositBankGoldMyNameActionBankDepositGoldPost(ctx context.Context, req *DepositWithdrawGoldSchema, params ActionDepositBankGoldMyNameActionBankDepositGoldPostParams) (r ActionDepositBankGoldMyNameActionBankDepositGoldPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionDepositBankMyNameActionBankDepositPost implements action_deposit_bank_my__name__action_bank_deposit_post operation.
//
// Deposit an item in a bank on the character's map.
//
// POST /my/{name}/action/bank/deposit
func (UnimplementedHandler) ActionDepositBankMyNameActionBankDepositPost(ctx context.Context, req *SimpleItemSchema, params ActionDepositBankMyNameActionBankDepositPostParams) (r ActionDepositBankMyNameActionBankDepositPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionEquipItemMyNameActionEquipPost implements action_equip_item_my__name__action_equip_post operation.
//
// Equip an item on your character.
//
// POST /my/{name}/action/equip
func (UnimplementedHandler) ActionEquipItemMyNameActionEquipPost(ctx context.Context, req *EquipSchema, params ActionEquipItemMyNameActionEquipPostParams) (r ActionEquipItemMyNameActionEquipPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionFightMyNameActionFightPost implements action_fight_my__name__action_fight_post operation.
//
// Start a fight against a monster on the character's map.
//
// POST /my/{name}/action/fight
func (UnimplementedHandler) ActionFightMyNameActionFightPost(ctx context.Context, params ActionFightMyNameActionFightPostParams) (r ActionFightMyNameActionFightPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionGatheringMyNameActionGatheringPost implements action_gathering_my__name__action_gathering_post operation.
//
// Harvest a resource on the character's map.
//
// POST /my/{name}/action/gathering
func (UnimplementedHandler) ActionGatheringMyNameActionGatheringPost(ctx context.Context, params ActionGatheringMyNameActionGatheringPostParams) (r ActionGatheringMyNameActionGatheringPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionGeBuyItemMyNameActionGeBuyPost implements action_ge_buy_item_my__name__action_ge_buy_post operation.
//
// Buy an item at the Grand Exchange on the character's map.
//
// POST /my/{name}/action/ge/buy
func (UnimplementedHandler) ActionGeBuyItemMyNameActionGeBuyPost(ctx context.Context, req *GETransactionItemSchema, params ActionGeBuyItemMyNameActionGeBuyPostParams) (r ActionGeBuyItemMyNameActionGeBuyPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionGeSellItemMyNameActionGeSellPost implements action_ge_sell_item_my__name__action_ge_sell_post operation.
//
// Sell an item at the Grand Exchange on the character's map.
//
// POST /my/{name}/action/ge/sell
func (UnimplementedHandler) ActionGeSellItemMyNameActionGeSellPost(ctx context.Context, req *GETransactionItemSchema, params ActionGeSellItemMyNameActionGeSellPostParams) (r ActionGeSellItemMyNameActionGeSellPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionMoveMyNameActionMovePost implements action_move_my__name__action_move_post operation.
//
// Moves a character on the map using the map's X and Y position.
//
// POST /my/{name}/action/move
func (UnimplementedHandler) ActionMoveMyNameActionMovePost(ctx context.Context, req *DestinationSchema, params ActionMoveMyNameActionMovePostParams) (r ActionMoveMyNameActionMovePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionRecyclingMyNameActionRecyclingPost implements action_recycling_my__name__action_recycling_post operation.
//
// Recyling an item. The character must be on a map with a workshop (only for equipments and weapons).
//
// POST /my/{name}/action/recycling
func (UnimplementedHandler) ActionRecyclingMyNameActionRecyclingPost(ctx context.Context, req *RecyclingSchema, params ActionRecyclingMyNameActionRecyclingPostParams) (r ActionRecyclingMyNameActionRecyclingPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionTaskExchangeMyNameActionTaskExchangePost implements action_task_exchange_my__name__action_task_exchange_post operation.
//
// Exchange 3 tasks coins for a random reward. Rewards are exclusive resources for crafting  items.
//
// POST /my/{name}/action/task/exchange
func (UnimplementedHandler) ActionTaskExchangeMyNameActionTaskExchangePost(ctx context.Context, params ActionTaskExchangeMyNameActionTaskExchangePostParams) (r ActionTaskExchangeMyNameActionTaskExchangePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionUnequipItemMyNameActionUnequipPost implements action_unequip_item_my__name__action_unequip_post operation.
//
// Unequip an item on your character.
//
// POST /my/{name}/action/unequip
func (UnimplementedHandler) ActionUnequipItemMyNameActionUnequipPost(ctx context.Context, req *UnequipSchema, params ActionUnequipItemMyNameActionUnequipPostParams) (r ActionUnequipItemMyNameActionUnequipPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionWithdrawBankGoldMyNameActionBankWithdrawGoldPost implements action_withdraw_bank_gold_my__name__action_bank_withdraw_gold_post operation.
//
// Withdraw gold from your bank.
//
// POST /my/{name}/action/bank/withdraw/gold
func (UnimplementedHandler) ActionWithdrawBankGoldMyNameActionBankWithdrawGoldPost(ctx context.Context, req *DepositWithdrawGoldSchema, params ActionWithdrawBankGoldMyNameActionBankWithdrawGoldPostParams) (r ActionWithdrawBankGoldMyNameActionBankWithdrawGoldPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ActionWithdrawBankMyNameActionBankWithdrawPost implements action_withdraw_bank_my__name__action_bank_withdraw_post operation.
//
// Take an item from your bank and put it in the character's inventory.
//
// POST /my/{name}/action/bank/withdraw
func (UnimplementedHandler) ActionWithdrawBankMyNameActionBankWithdrawPost(ctx context.Context, req *SimpleItemSchema, params ActionWithdrawBankMyNameActionBankWithdrawPostParams) (r ActionWithdrawBankMyNameActionBankWithdrawPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ChangePasswordMyChangePasswordPost implements change_password_my_change_password_post operation.
//
// Change your account password. Changing the password reset the account token.
//
// POST /my/change_password
func (UnimplementedHandler) ChangePasswordMyChangePasswordPost(ctx context.Context, req *ChangePassword) (r ChangePasswordMyChangePasswordPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAccountAccountsCreatePost implements create_account_accounts_create_post operation.
//
// Create an account.
//
// POST /accounts/create
func (UnimplementedHandler) CreateAccountAccountsCreatePost(ctx context.Context, req *AddAccountSchema) (r CreateAccountAccountsCreatePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCharacterCharactersCreatePost implements create_character_characters_create_post operation.
//
// Create new character on your account. You can create up to 5 characters.
//
// POST /characters/create
func (UnimplementedHandler) CreateCharacterCharactersCreatePost(ctx context.Context, req *AddCharacterSchema) (r CreateCharacterCharactersCreatePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GenerateTokenTokenPost implements generate_token_token__post operation.
//
// Use your account as HTTPBasic Auth to generate your token to use the API. You can also generate
// your token directly on the website.
//
// POST /token/
func (UnimplementedHandler) GenerateTokenTokenPost(ctx context.Context) (r GenerateTokenTokenPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllCharactersCharactersGet implements get_all_characters_characters__get operation.
//
// Fetch characters details.
//
// GET /characters/
func (UnimplementedHandler) GetAllCharactersCharactersGet(ctx context.Context, params GetAllCharactersCharactersGetParams) (r GetAllCharactersCharactersGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllCharactersLogsMyLogsGet implements get_all_characters_logs_my_logs_get operation.
//
// History of the last 100 actions of all your characters.
//
// GET /my/logs
func (UnimplementedHandler) GetAllCharactersLogsMyLogsGet(ctx context.Context, params GetAllCharactersLogsMyLogsGetParams) (r GetAllCharactersLogsMyLogsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllEventsEventsGet implements get_all_events_events__get operation.
//
// Fetch events details.
//
// GET /events/
func (UnimplementedHandler) GetAllEventsEventsGet(ctx context.Context, params GetAllEventsEventsGetParams) (r GetAllEventsEventsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllGeItemsGeGet implements get_all_ge_items_ge__get operation.
//
// Fetch Grand Exchange items details.
//
// GET /ge/
func (UnimplementedHandler) GetAllGeItemsGeGet(ctx context.Context, params GetAllGeItemsGeGetParams) (r GetAllGeItemsGeGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllItemsItemsGet implements get_all_items_items__get operation.
//
// Fetch items details.
//
// GET /items/
func (UnimplementedHandler) GetAllItemsItemsGet(ctx context.Context, params GetAllItemsItemsGetParams) (r GetAllItemsItemsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllMapsMapsGet implements get_all_maps_maps__get operation.
//
// Fetch maps details.
//
// GET /maps/
func (UnimplementedHandler) GetAllMapsMapsGet(ctx context.Context, params GetAllMapsMapsGetParams) (r GetAllMapsMapsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllMonstersMonstersGet implements get_all_monsters_monsters__get operation.
//
// Fetch monsters details.
//
// GET /monsters/
func (UnimplementedHandler) GetAllMonstersMonstersGet(ctx context.Context, params GetAllMonstersMonstersGetParams) (r GetAllMonstersMonstersGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllResourcesResourcesGet implements get_all_resources_resources__get operation.
//
// Fetch resources details.
//
// GET /resources/
func (UnimplementedHandler) GetAllResourcesResourcesGet(ctx context.Context, params GetAllResourcesResourcesGetParams) (r GetAllResourcesResourcesGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBankGoldsMyBankGoldGet implements get_bank_golds_my_bank_gold_get operation.
//
// Fetch golds in your bank.
//
// GET /my/bank/gold
func (UnimplementedHandler) GetBankGoldsMyBankGoldGet(ctx context.Context) (r *GoldBankResponseSchema, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBankItemsMyBankItemsGet implements get_bank_items_my_bank_items_get operation.
//
// Fetch all items in your bank.
//
// GET /my/bank/items
func (UnimplementedHandler) GetBankItemsMyBankItemsGet(ctx context.Context, params GetBankItemsMyBankItemsGetParams) (r GetBankItemsMyBankItemsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCharacterCharactersNameGet implements get_character_characters__name__get operation.
//
// Retrieve the details of a character.
//
// GET /characters/{name}
func (UnimplementedHandler) GetCharacterCharactersNameGet(ctx context.Context, params GetCharacterCharactersNameGetParams) (r GetCharacterCharactersNameGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCharacterLogsMyNameLogsGet implements get_character_logs_my__name__logs_get operation.
//
// History of your character's last 100 actions.
//
// GET /my/{name}/logs
func (UnimplementedHandler) GetCharacterLogsMyNameLogsGet(ctx context.Context, params GetCharacterLogsMyNameLogsGetParams) (r GetCharacterLogsMyNameLogsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGeItemGeCodeGet implements get_ge_item_ge__code__get operation.
//
// Retrieve the details of a Grand Exchange item.
//
// GET /ge/{code}
func (UnimplementedHandler) GetGeItemGeCodeGet(ctx context.Context, params GetGeItemGeCodeGetParams) (r GetGeItemGeCodeGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetItemItemsCodeGet implements get_item_items__code__get operation.
//
// Retrieve the details of a item.
//
// GET /items/{code}
func (UnimplementedHandler) GetItemItemsCodeGet(ctx context.Context, params GetItemItemsCodeGetParams) (r GetItemItemsCodeGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMapMapsXYGet implements get_map_maps__x___y__get operation.
//
// Retrieve the details of a map.
//
// GET /maps/{x}/{y}
func (UnimplementedHandler) GetMapMapsXYGet(ctx context.Context, params GetMapMapsXYGetParams) (r GetMapMapsXYGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMonsterMonstersCodeGet implements get_monster_monsters__code__get operation.
//
// Retrieve the details of a monster.
//
// GET /monsters/{code}
func (UnimplementedHandler) GetMonsterMonstersCodeGet(ctx context.Context, params GetMonsterMonstersCodeGetParams) (r GetMonsterMonstersCodeGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyCharactersMyCharactersGet implements get_my_characters_my_characters_get operation.
//
// List of your characters.
//
// GET /my/characters
func (UnimplementedHandler) GetMyCharactersMyCharactersGet(ctx context.Context) (r GetMyCharactersMyCharactersGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetResourcesResourcesCodeGet implements get_resources_resources__code__get operation.
//
// Retrieve the details of a resource.
//
// GET /resources/{code}
func (UnimplementedHandler) GetResourcesResourcesCodeGet(ctx context.Context, params GetResourcesResourcesCodeGetParams) (r GetResourcesResourcesCodeGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStatusGet implements get_status__get operation.
//
// Return the status of the game server.
//
// GET /
func (UnimplementedHandler) GetStatusGet(ctx context.Context) (r *StatusResponseSchema, _ error) {
	return r, ht.ErrNotImplemented
}
