// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleHTTPBasic handles HTTPBasic security.
	HandleHTTPBasic(ctx context.Context, operationName string, t HTTPBasic) (context.Context, error)
	// HandleJWTBearer handles JWTBearer security.
	HandleJWTBearer(ctx context.Context, operationName string, t JWTBearer) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

func (s *Server) securityHTTPBasic(ctx context.Context, operationName string, req *http.Request) (context.Context, bool, error) {
	var t HTTPBasic
	if _, ok := findAuthorization(req.Header, "Basic"); !ok {
		return ctx, false, nil
	}
	username, password, ok := req.BasicAuth()
	if !ok {
		return nil, false, errors.New("invalid basic auth")
	}
	t.Username = username
	t.Password = password
	rctx, err := s.sec.HandleHTTPBasic(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}
func (s *Server) securityJWTBearer(ctx context.Context, operationName string, req *http.Request) (context.Context, bool, error) {
	var t JWTBearer
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	rctx, err := s.sec.HandleJWTBearer(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// HTTPBasic provides HTTPBasic security value.
	HTTPBasic(ctx context.Context, operationName string) (HTTPBasic, error)
	// JWTBearer provides JWTBearer security value.
	JWTBearer(ctx context.Context, operationName string) (JWTBearer, error)
}

func (s *Client) securityHTTPBasic(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.HTTPBasic(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"HTTPBasic\"")
	}
	req.SetBasicAuth(t.Username, t.Password)
	return nil
}
func (s *Client) securityJWTBearer(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.JWTBearer(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"JWTBearer\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
