// Code generated by ogen, DO NOT EDIT.

package openapi

// setDefaults set default value of fields.
func (s *CraftingSchema) setDefaults() {
	{
		val := int(1)
		s.Quantity.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RecyclingSchema) setDefaults() {
	{
		val := int(1)
		s.Quantity.SetTo(val)
	}
}
