// Code generated by ogen, DO NOT EDIT.
package openapi

type ActionAcceptNewTaskMyNameActionTaskNewPostRes interface {
	actionAcceptNewTaskMyNameActionTaskNewPostRes()
}

type ActionCompleteTaskMyNameActionTaskCompletePostRes interface {
	actionCompleteTaskMyNameActionTaskCompletePostRes()
}

type ActionCraftingMyNameActionCraftingPostRes interface {
	actionCraftingMyNameActionCraftingPostRes()
}

type ActionDeleteItemMyNameActionDeletePostRes interface {
	actionDeleteItemMyNameActionDeletePostRes()
}

type ActionDepositBankGoldMyNameActionBankDepositGoldPostRes interface {
	actionDepositBankGoldMyNameActionBankDepositGoldPostRes()
}

type ActionDepositBankMyNameActionBankDepositPostRes interface {
	actionDepositBankMyNameActionBankDepositPostRes()
}

type ActionEquipItemMyNameActionEquipPostRes interface {
	actionEquipItemMyNameActionEquipPostRes()
}

type ActionFightMyNameActionFightPostRes interface {
	actionFightMyNameActionFightPostRes()
}

type ActionGatheringMyNameActionGatheringPostRes interface {
	actionGatheringMyNameActionGatheringPostRes()
}

type ActionGeBuyItemMyNameActionGeBuyPostRes interface {
	actionGeBuyItemMyNameActionGeBuyPostRes()
}

type ActionGeSellItemMyNameActionGeSellPostRes interface {
	actionGeSellItemMyNameActionGeSellPostRes()
}

type ActionMoveMyNameActionMovePostRes interface {
	actionMoveMyNameActionMovePostRes()
}

type ActionRecyclingMyNameActionRecyclingPostRes interface {
	actionRecyclingMyNameActionRecyclingPostRes()
}

type ActionTaskExchangeMyNameActionTaskExchangePostRes interface {
	actionTaskExchangeMyNameActionTaskExchangePostRes()
}

type ActionUnequipItemMyNameActionUnequipPostRes interface {
	actionUnequipItemMyNameActionUnequipPostRes()
}

type ActionWithdrawBankGoldMyNameActionBankWithdrawGoldPostRes interface {
	actionWithdrawBankGoldMyNameActionBankWithdrawGoldPostRes()
}

type ActionWithdrawBankMyNameActionBankWithdrawPostRes interface {
	actionWithdrawBankMyNameActionBankWithdrawPostRes()
}

type ChangePasswordMyChangePasswordPostRes interface {
	changePasswordMyChangePasswordPostRes()
}

type CreateAccountAccountsCreatePostRes interface {
	createAccountAccountsCreatePostRes()
}

type CreateCharacterCharactersCreatePostRes interface {
	createCharacterCharactersCreatePostRes()
}

type GenerateTokenTokenPostRes interface {
	generateTokenTokenPostRes()
}

type GetAllCharactersCharactersGetRes interface {
	getAllCharactersCharactersGetRes()
}

type GetAllCharactersLogsMyLogsGetRes interface {
	getAllCharactersLogsMyLogsGetRes()
}

type GetAllEventsEventsGetRes interface {
	getAllEventsEventsGetRes()
}

type GetAllGeItemsGeGetRes interface {
	getAllGeItemsGeGetRes()
}

type GetAllItemsItemsGetRes interface {
	getAllItemsItemsGetRes()
}

type GetAllMapsMapsGetRes interface {
	getAllMapsMapsGetRes()
}

type GetAllMonstersMonstersGetRes interface {
	getAllMonstersMonstersGetRes()
}

type GetAllResourcesResourcesGetRes interface {
	getAllResourcesResourcesGetRes()
}

type GetBankItemsMyBankItemsGetRes interface {
	getBankItemsMyBankItemsGetRes()
}

type GetCharacterCharactersNameGetRes interface {
	getCharacterCharactersNameGetRes()
}

type GetCharacterLogsMyNameLogsGetRes interface {
	getCharacterLogsMyNameLogsGetRes()
}

type GetGeItemGeCodeGetRes interface {
	getGeItemGeCodeGetRes()
}

type GetItemItemsCodeGetRes interface {
	getItemItemsCodeGetRes()
}

type GetMapMapsXYGetRes interface {
	getMapMapsXYGetRes()
}

type GetMonsterMonstersCodeGetRes interface {
	getMonsterMonstersCodeGetRes()
}

type GetMyCharactersMyCharactersGetRes interface {
	getMyCharactersMyCharactersGetRes()
}

type GetResourcesResourcesCodeGetRes interface {
	getResourcesResourcesCodeGetRes()
}
