// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [2]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"
			origElem := elem
			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				switch r.Method {
				case "GET":
					s.handleGetStatusGetRequest([0]string{}, elemIsEscaped, w, r)
				default:
					s.notAllowed(w, r, "GET")
				}

				return
			}
			switch elem[0] {
			case 'a': // Prefix: "accounts/create"
				origElem := elem
				if l := len("accounts/create"); len(elem) >= l && elem[0:l] == "accounts/create" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleCreateAccountAccountsCreatePostRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "POST")
					}

					return
				}

				elem = origElem
			case 'c': // Prefix: "characters/"
				origElem := elem
				if l := len("characters/"); len(elem) >= l && elem[0:l] == "characters/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleGetAllCharactersCharactersGetRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}
				switch elem[0] {
				case 'c': // Prefix: "create"
					origElem := elem
					if l := len("create"); len(elem) >= l && elem[0:l] == "create" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleCreateCharacterCharactersCreatePostRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "POST")
						}

						return
					}

					elem = origElem
				}
				// Param: "name"
				// Leaf parameter
				args[0] = elem
				elem = ""

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetCharacterCharactersNameGetRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

				elem = origElem
			case 'e': // Prefix: "events/"
				origElem := elem
				if l := len("events/"); len(elem) >= l && elem[0:l] == "events/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetAllEventsEventsGetRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

				elem = origElem
			case 'g': // Prefix: "ge/"
				origElem := elem
				if l := len("ge/"); len(elem) >= l && elem[0:l] == "ge/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleGetAllGeItemsGeGetRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}
				// Param: "code"
				// Leaf parameter
				args[0] = elem
				elem = ""

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetGeItemGeCodeGetRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

				elem = origElem
			case 'i': // Prefix: "items/"
				origElem := elem
				if l := len("items/"); len(elem) >= l && elem[0:l] == "items/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleGetAllItemsItemsGetRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}
				// Param: "code"
				// Leaf parameter
				args[0] = elem
				elem = ""

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetItemItemsCodeGetRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

				elem = origElem
			case 'm': // Prefix: "m"
				origElem := elem
				if l := len("m"); len(elem) >= l && elem[0:l] == "m" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "aps/"
					origElem := elem
					if l := len("aps/"); len(elem) >= l && elem[0:l] == "aps/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetAllMapsMapsGetRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}
					// Param: "x"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/"
						origElem := elem
						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "y"
						// Leaf parameter
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetMapMapsXYGetRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

						elem = origElem
					}

					elem = origElem
				case 'o': // Prefix: "onsters/"
					origElem := elem
					if l := len("onsters/"); len(elem) >= l && elem[0:l] == "onsters/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetAllMonstersMonstersGetRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}
					// Param: "code"
					// Leaf parameter
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetMonsterMonstersCodeGetRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

					elem = origElem
				case 'y': // Prefix: "y/"
					origElem := elem
					if l := len("y/"); len(elem) >= l && elem[0:l] == "y/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'b': // Prefix: "bank/"
						origElem := elem
						if l := len("bank/"); len(elem) >= l && elem[0:l] == "bank/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'g': // Prefix: "gold"
							origElem := elem
							if l := len("gold"); len(elem) >= l && elem[0:l] == "gold" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetBankGoldsMyBankGoldGetRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

							elem = origElem
						case 'i': // Prefix: "items"
							origElem := elem
							if l := len("items"); len(elem) >= l && elem[0:l] == "items" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetBankItemsMyBankItemsGetRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

							elem = origElem
						}

						elem = origElem
					case 'c': // Prefix: "cha"
						origElem := elem
						if l := len("cha"); len(elem) >= l && elem[0:l] == "cha" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'n': // Prefix: "nge_password"
							origElem := elem
							if l := len("nge_password"); len(elem) >= l && elem[0:l] == "nge_password" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleChangePasswordMyChangePasswordPostRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "POST")
								}

								return
							}

							elem = origElem
						case 'r': // Prefix: "racters"
							origElem := elem
							if l := len("racters"); len(elem) >= l && elem[0:l] == "racters" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetMyCharactersMyCharactersGetRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

							elem = origElem
						}

						elem = origElem
					case 'l': // Prefix: "logs"
						origElem := elem
						if l := len("logs"); len(elem) >= l && elem[0:l] == "logs" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetAllCharactersLogsMyLogsGetRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

						elem = origElem
					}
					// Param: "name"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/"
						origElem := elem
						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "action/"
							origElem := elem
							if l := len("action/"); len(elem) >= l && elem[0:l] == "action/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'b': // Prefix: "bank/"
								origElem := elem
								if l := len("bank/"); len(elem) >= l && elem[0:l] == "bank/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'd': // Prefix: "deposit"
									origElem := elem
									if l := len("deposit"); len(elem) >= l && elem[0:l] == "deposit" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										switch r.Method {
										case "POST":
											s.handleActionDepositBankMyNameActionBankDepositPostRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}
									switch elem[0] {
									case '/': // Prefix: "/gold"
										origElem := elem
										if l := len("/gold"); len(elem) >= l && elem[0:l] == "/gold" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "POST":
												s.handleActionDepositBankGoldMyNameActionBankDepositGoldPostRequest([1]string{
													args[0],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, "POST")
											}

											return
										}

										elem = origElem
									}

									elem = origElem
								case 'w': // Prefix: "withdraw"
									origElem := elem
									if l := len("withdraw"); len(elem) >= l && elem[0:l] == "withdraw" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										switch r.Method {
										case "POST":
											s.handleActionWithdrawBankMyNameActionBankWithdrawPostRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}
									switch elem[0] {
									case '/': // Prefix: "/gold"
										origElem := elem
										if l := len("/gold"); len(elem) >= l && elem[0:l] == "/gold" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "POST":
												s.handleActionWithdrawBankGoldMyNameActionBankWithdrawGoldPostRequest([1]string{
													args[0],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, "POST")
											}

											return
										}

										elem = origElem
									}

									elem = origElem
								}

								elem = origElem
							case 'c': // Prefix: "crafting"
								origElem := elem
								if l := len("crafting"); len(elem) >= l && elem[0:l] == "crafting" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleActionCraftingMyNameActionCraftingPostRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

								elem = origElem
							case 'd': // Prefix: "delete"
								origElem := elem
								if l := len("delete"); len(elem) >= l && elem[0:l] == "delete" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleActionDeleteItemMyNameActionDeletePostRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

								elem = origElem
							case 'e': // Prefix: "equip"
								origElem := elem
								if l := len("equip"); len(elem) >= l && elem[0:l] == "equip" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleActionEquipItemMyNameActionEquipPostRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

								elem = origElem
							case 'f': // Prefix: "fight"
								origElem := elem
								if l := len("fight"); len(elem) >= l && elem[0:l] == "fight" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleActionFightMyNameActionFightPostRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

								elem = origElem
							case 'g': // Prefix: "g"
								origElem := elem
								if l := len("g"); len(elem) >= l && elem[0:l] == "g" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'a': // Prefix: "athering"
									origElem := elem
									if l := len("athering"); len(elem) >= l && elem[0:l] == "athering" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleActionGatheringMyNameActionGatheringPostRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}

									elem = origElem
								case 'e': // Prefix: "e/"
									origElem := elem
									if l := len("e/"); len(elem) >= l && elem[0:l] == "e/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'b': // Prefix: "buy"
										origElem := elem
										if l := len("buy"); len(elem) >= l && elem[0:l] == "buy" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "POST":
												s.handleActionGeBuyItemMyNameActionGeBuyPostRequest([1]string{
													args[0],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, "POST")
											}

											return
										}

										elem = origElem
									case 's': // Prefix: "sell"
										origElem := elem
										if l := len("sell"); len(elem) >= l && elem[0:l] == "sell" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "POST":
												s.handleActionGeSellItemMyNameActionGeSellPostRequest([1]string{
													args[0],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, "POST")
											}

											return
										}

										elem = origElem
									}

									elem = origElem
								}

								elem = origElem
							case 'm': // Prefix: "move"
								origElem := elem
								if l := len("move"); len(elem) >= l && elem[0:l] == "move" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleActionMoveMyNameActionMovePostRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

								elem = origElem
							case 'r': // Prefix: "recycling"
								origElem := elem
								if l := len("recycling"); len(elem) >= l && elem[0:l] == "recycling" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleActionRecyclingMyNameActionRecyclingPostRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

								elem = origElem
							case 't': // Prefix: "task/"
								origElem := elem
								if l := len("task/"); len(elem) >= l && elem[0:l] == "task/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'c': // Prefix: "complete"
									origElem := elem
									if l := len("complete"); len(elem) >= l && elem[0:l] == "complete" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleActionCompleteTaskMyNameActionTaskCompletePostRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}

									elem = origElem
								case 'e': // Prefix: "exchange"
									origElem := elem
									if l := len("exchange"); len(elem) >= l && elem[0:l] == "exchange" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleActionTaskExchangeMyNameActionTaskExchangePostRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}

									elem = origElem
								case 'n': // Prefix: "new"
									origElem := elem
									if l := len("new"); len(elem) >= l && elem[0:l] == "new" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleActionAcceptNewTaskMyNameActionTaskNewPostRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, "POST")
										}

										return
									}

									elem = origElem
								}

								elem = origElem
							case 'u': // Prefix: "unequip"
								origElem := elem
								if l := len("unequip"); len(elem) >= l && elem[0:l] == "unequip" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleActionUnequipItemMyNameActionUnequipPostRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, "POST")
									}

									return
								}

								elem = origElem
							}

							elem = origElem
						case 'l': // Prefix: "logs"
							origElem := elem
							if l := len("logs"); len(elem) >= l && elem[0:l] == "logs" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetCharacterLogsMyNameLogsGetRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

							elem = origElem
						}

						elem = origElem
					}

					elem = origElem
				}

				elem = origElem
			case 'r': // Prefix: "resources/"
				origElem := elem
				if l := len("resources/"); len(elem) >= l && elem[0:l] == "resources/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleGetAllResourcesResourcesGetRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}
				// Param: "code"
				// Leaf parameter
				args[0] = elem
				elem = ""

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetResourcesResourcesCodeGetRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

				elem = origElem
			case 't': // Prefix: "token/"
				origElem := elem
				if l := len("token/"); len(elem) >= l && elem[0:l] == "token/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleGenerateTokenTokenPostRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "POST")
					}

					return
				}

				elem = origElem
			}

			elem = origElem
		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name        string
	summary     string
	operationID string
	pathPattern string
	count       int
	args        [2]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"
			origElem := elem
			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				switch method {
				case "GET":
					r.name = "GetStatusGet"
					r.summary = "Get Status"
					r.operationID = "get_status__get"
					r.pathPattern = "/"
					r.args = args
					r.count = 0
					return r, true
				default:
					return
				}
			}
			switch elem[0] {
			case 'a': // Prefix: "accounts/create"
				origElem := elem
				if l := len("accounts/create"); len(elem) >= l && elem[0:l] == "accounts/create" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "POST":
						r.name = "CreateAccountAccountsCreatePost"
						r.summary = "Create Account"
						r.operationID = "create_account_accounts_create_post"
						r.pathPattern = "/accounts/create"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 'c': // Prefix: "characters/"
				origElem := elem
				if l := len("characters/"); len(elem) >= l && elem[0:l] == "characters/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = "GetAllCharactersCharactersGet"
						r.summary = "Get All Characters"
						r.operationID = "get_all_characters_characters__get"
						r.pathPattern = "/characters/"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case 'c': // Prefix: "create"
					origElem := elem
					if l := len("create"); len(elem) >= l && elem[0:l] == "create" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = "CreateCharacterCharactersCreatePost"
							r.summary = "Create Character"
							r.operationID = "create_character_characters_create_post"
							r.pathPattern = "/characters/create"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

					elem = origElem
				}
				// Param: "name"
				// Leaf parameter
				args[0] = elem
				elem = ""

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = "GetCharacterCharactersNameGet"
						r.summary = "Get Character"
						r.operationID = "get_character_characters__name__get"
						r.pathPattern = "/characters/{name}"
						r.args = args
						r.count = 1
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 'e': // Prefix: "events/"
				origElem := elem
				if l := len("events/"); len(elem) >= l && elem[0:l] == "events/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = "GetAllEventsEventsGet"
						r.summary = "Get All Events"
						r.operationID = "get_all_events_events__get"
						r.pathPattern = "/events/"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 'g': // Prefix: "ge/"
				origElem := elem
				if l := len("ge/"); len(elem) >= l && elem[0:l] == "ge/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = "GetAllGeItemsGeGet"
						r.summary = "Get All Ge Items"
						r.operationID = "get_all_ge_items_ge__get"
						r.pathPattern = "/ge/"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				// Param: "code"
				// Leaf parameter
				args[0] = elem
				elem = ""

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = "GetGeItemGeCodeGet"
						r.summary = "Get Ge Item"
						r.operationID = "get_ge_item_ge__code__get"
						r.pathPattern = "/ge/{code}"
						r.args = args
						r.count = 1
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 'i': // Prefix: "items/"
				origElem := elem
				if l := len("items/"); len(elem) >= l && elem[0:l] == "items/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = "GetAllItemsItemsGet"
						r.summary = "Get All Items"
						r.operationID = "get_all_items_items__get"
						r.pathPattern = "/items/"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				// Param: "code"
				// Leaf parameter
				args[0] = elem
				elem = ""

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = "GetItemItemsCodeGet"
						r.summary = "Get Item"
						r.operationID = "get_item_items__code__get"
						r.pathPattern = "/items/{code}"
						r.args = args
						r.count = 1
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 'm': // Prefix: "m"
				origElem := elem
				if l := len("m"); len(elem) >= l && elem[0:l] == "m" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "aps/"
					origElem := elem
					if l := len("aps/"); len(elem) >= l && elem[0:l] == "aps/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = "GetAllMapsMapsGet"
							r.summary = "Get All Maps"
							r.operationID = "get_all_maps_maps__get"
							r.pathPattern = "/maps/"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					// Param: "x"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/"
						origElem := elem
						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "y"
						// Leaf parameter
						args[1] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = "GetMapMapsXYGet"
								r.summary = "Get Map"
								r.operationID = "get_map_maps__x___y__get"
								r.pathPattern = "/maps/{x}/{y}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}

						elem = origElem
					}

					elem = origElem
				case 'o': // Prefix: "onsters/"
					origElem := elem
					if l := len("onsters/"); len(elem) >= l && elem[0:l] == "onsters/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = "GetAllMonstersMonstersGet"
							r.summary = "Get All Monsters"
							r.operationID = "get_all_monsters_monsters__get"
							r.pathPattern = "/monsters/"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					// Param: "code"
					// Leaf parameter
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = "GetMonsterMonstersCodeGet"
							r.summary = "Get Monster"
							r.operationID = "get_monster_monsters__code__get"
							r.pathPattern = "/monsters/{code}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

					elem = origElem
				case 'y': // Prefix: "y/"
					origElem := elem
					if l := len("y/"); len(elem) >= l && elem[0:l] == "y/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'b': // Prefix: "bank/"
						origElem := elem
						if l := len("bank/"); len(elem) >= l && elem[0:l] == "bank/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'g': // Prefix: "gold"
							origElem := elem
							if l := len("gold"); len(elem) >= l && elem[0:l] == "gold" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = "GetBankGoldsMyBankGoldGet"
									r.summary = "Get Bank Golds"
									r.operationID = "get_bank_golds_my_bank_gold_get"
									r.pathPattern = "/my/bank/gold"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

							elem = origElem
						case 'i': // Prefix: "items"
							origElem := elem
							if l := len("items"); len(elem) >= l && elem[0:l] == "items" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = "GetBankItemsMyBankItemsGet"
									r.summary = "Get Bank Items"
									r.operationID = "get_bank_items_my_bank_items_get"
									r.pathPattern = "/my/bank/items"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

							elem = origElem
						}

						elem = origElem
					case 'c': // Prefix: "cha"
						origElem := elem
						if l := len("cha"); len(elem) >= l && elem[0:l] == "cha" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'n': // Prefix: "nge_password"
							origElem := elem
							if l := len("nge_password"); len(elem) >= l && elem[0:l] == "nge_password" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = "ChangePasswordMyChangePasswordPost"
									r.summary = "Change Password"
									r.operationID = "change_password_my_change_password_post"
									r.pathPattern = "/my/change_password"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

							elem = origElem
						case 'r': // Prefix: "racters"
							origElem := elem
							if l := len("racters"); len(elem) >= l && elem[0:l] == "racters" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = "GetMyCharactersMyCharactersGet"
									r.summary = "Get My Characters"
									r.operationID = "get_my_characters_my_characters_get"
									r.pathPattern = "/my/characters"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

							elem = origElem
						}

						elem = origElem
					case 'l': // Prefix: "logs"
						origElem := elem
						if l := len("logs"); len(elem) >= l && elem[0:l] == "logs" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = "GetAllCharactersLogsMyLogsGet"
								r.summary = "Get All Characters Logs"
								r.operationID = "get_all_characters_logs_my_logs_get"
								r.pathPattern = "/my/logs"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

						elem = origElem
					}
					// Param: "name"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/"
						origElem := elem
						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "action/"
							origElem := elem
							if l := len("action/"); len(elem) >= l && elem[0:l] == "action/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'b': // Prefix: "bank/"
								origElem := elem
								if l := len("bank/"); len(elem) >= l && elem[0:l] == "bank/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'd': // Prefix: "deposit"
									origElem := elem
									if l := len("deposit"); len(elem) >= l && elem[0:l] == "deposit" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										switch method {
										case "POST":
											r.name = "ActionDepositBankMyNameActionBankDepositPost"
											r.summary = "Action Deposit Bank"
											r.operationID = "action_deposit_bank_my__name__action_bank_deposit_post"
											r.pathPattern = "/my/{name}/action/bank/deposit"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}
									switch elem[0] {
									case '/': // Prefix: "/gold"
										origElem := elem
										if l := len("/gold"); len(elem) >= l && elem[0:l] == "/gold" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "POST":
												r.name = "ActionDepositBankGoldMyNameActionBankDepositGoldPost"
												r.summary = "Action Deposit Bank Gold"
												r.operationID = "action_deposit_bank_gold_my__name__action_bank_deposit_gold_post"
												r.pathPattern = "/my/{name}/action/bank/deposit/gold"
												r.args = args
												r.count = 1
												return r, true
											default:
												return
											}
										}

										elem = origElem
									}

									elem = origElem
								case 'w': // Prefix: "withdraw"
									origElem := elem
									if l := len("withdraw"); len(elem) >= l && elem[0:l] == "withdraw" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										switch method {
										case "POST":
											r.name = "ActionWithdrawBankMyNameActionBankWithdrawPost"
											r.summary = "Action Withdraw Bank"
											r.operationID = "action_withdraw_bank_my__name__action_bank_withdraw_post"
											r.pathPattern = "/my/{name}/action/bank/withdraw"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}
									switch elem[0] {
									case '/': // Prefix: "/gold"
										origElem := elem
										if l := len("/gold"); len(elem) >= l && elem[0:l] == "/gold" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "POST":
												r.name = "ActionWithdrawBankGoldMyNameActionBankWithdrawGoldPost"
												r.summary = "Action Withdraw Bank Gold"
												r.operationID = "action_withdraw_bank_gold_my__name__action_bank_withdraw_gold_post"
												r.pathPattern = "/my/{name}/action/bank/withdraw/gold"
												r.args = args
												r.count = 1
												return r, true
											default:
												return
											}
										}

										elem = origElem
									}

									elem = origElem
								}

								elem = origElem
							case 'c': // Prefix: "crafting"
								origElem := elem
								if l := len("crafting"); len(elem) >= l && elem[0:l] == "crafting" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = "ActionCraftingMyNameActionCraftingPost"
										r.summary = "Action Crafting"
										r.operationID = "action_crafting_my__name__action_crafting_post"
										r.pathPattern = "/my/{name}/action/crafting"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

								elem = origElem
							case 'd': // Prefix: "delete"
								origElem := elem
								if l := len("delete"); len(elem) >= l && elem[0:l] == "delete" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = "ActionDeleteItemMyNameActionDeletePost"
										r.summary = "Action Delete Item"
										r.operationID = "action_delete_item_my__name__action_delete_post"
										r.pathPattern = "/my/{name}/action/delete"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

								elem = origElem
							case 'e': // Prefix: "equip"
								origElem := elem
								if l := len("equip"); len(elem) >= l && elem[0:l] == "equip" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = "ActionEquipItemMyNameActionEquipPost"
										r.summary = "Action Equip Item"
										r.operationID = "action_equip_item_my__name__action_equip_post"
										r.pathPattern = "/my/{name}/action/equip"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

								elem = origElem
							case 'f': // Prefix: "fight"
								origElem := elem
								if l := len("fight"); len(elem) >= l && elem[0:l] == "fight" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = "ActionFightMyNameActionFightPost"
										r.summary = "Action Fight"
										r.operationID = "action_fight_my__name__action_fight_post"
										r.pathPattern = "/my/{name}/action/fight"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

								elem = origElem
							case 'g': // Prefix: "g"
								origElem := elem
								if l := len("g"); len(elem) >= l && elem[0:l] == "g" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'a': // Prefix: "athering"
									origElem := elem
									if l := len("athering"); len(elem) >= l && elem[0:l] == "athering" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = "ActionGatheringMyNameActionGatheringPost"
											r.summary = "Action Gathering"
											r.operationID = "action_gathering_my__name__action_gathering_post"
											r.pathPattern = "/my/{name}/action/gathering"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

									elem = origElem
								case 'e': // Prefix: "e/"
									origElem := elem
									if l := len("e/"); len(elem) >= l && elem[0:l] == "e/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'b': // Prefix: "buy"
										origElem := elem
										if l := len("buy"); len(elem) >= l && elem[0:l] == "buy" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "POST":
												r.name = "ActionGeBuyItemMyNameActionGeBuyPost"
												r.summary = "Action Ge Buy Item"
												r.operationID = "action_ge_buy_item_my__name__action_ge_buy_post"
												r.pathPattern = "/my/{name}/action/ge/buy"
												r.args = args
												r.count = 1
												return r, true
											default:
												return
											}
										}

										elem = origElem
									case 's': // Prefix: "sell"
										origElem := elem
										if l := len("sell"); len(elem) >= l && elem[0:l] == "sell" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "POST":
												r.name = "ActionGeSellItemMyNameActionGeSellPost"
												r.summary = "Action Ge Sell Item"
												r.operationID = "action_ge_sell_item_my__name__action_ge_sell_post"
												r.pathPattern = "/my/{name}/action/ge/sell"
												r.args = args
												r.count = 1
												return r, true
											default:
												return
											}
										}

										elem = origElem
									}

									elem = origElem
								}

								elem = origElem
							case 'm': // Prefix: "move"
								origElem := elem
								if l := len("move"); len(elem) >= l && elem[0:l] == "move" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = "ActionMoveMyNameActionMovePost"
										r.summary = "Action Move"
										r.operationID = "action_move_my__name__action_move_post"
										r.pathPattern = "/my/{name}/action/move"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

								elem = origElem
							case 'r': // Prefix: "recycling"
								origElem := elem
								if l := len("recycling"); len(elem) >= l && elem[0:l] == "recycling" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = "ActionRecyclingMyNameActionRecyclingPost"
										r.summary = "Action Recycling"
										r.operationID = "action_recycling_my__name__action_recycling_post"
										r.pathPattern = "/my/{name}/action/recycling"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

								elem = origElem
							case 't': // Prefix: "task/"
								origElem := elem
								if l := len("task/"); len(elem) >= l && elem[0:l] == "task/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'c': // Prefix: "complete"
									origElem := elem
									if l := len("complete"); len(elem) >= l && elem[0:l] == "complete" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = "ActionCompleteTaskMyNameActionTaskCompletePost"
											r.summary = "Action Complete Task"
											r.operationID = "action_complete_task_my__name__action_task_complete_post"
											r.pathPattern = "/my/{name}/action/task/complete"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

									elem = origElem
								case 'e': // Prefix: "exchange"
									origElem := elem
									if l := len("exchange"); len(elem) >= l && elem[0:l] == "exchange" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = "ActionTaskExchangeMyNameActionTaskExchangePost"
											r.summary = "Action Task Exchange"
											r.operationID = "action_task_exchange_my__name__action_task_exchange_post"
											r.pathPattern = "/my/{name}/action/task/exchange"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

									elem = origElem
								case 'n': // Prefix: "new"
									origElem := elem
									if l := len("new"); len(elem) >= l && elem[0:l] == "new" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = "ActionAcceptNewTaskMyNameActionTaskNewPost"
											r.summary = "Action Accept New Task"
											r.operationID = "action_accept_new_task_my__name__action_task_new_post"
											r.pathPattern = "/my/{name}/action/task/new"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

									elem = origElem
								}

								elem = origElem
							case 'u': // Prefix: "unequip"
								origElem := elem
								if l := len("unequip"); len(elem) >= l && elem[0:l] == "unequip" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = "ActionUnequipItemMyNameActionUnequipPost"
										r.summary = "Action Unequip Item"
										r.operationID = "action_unequip_item_my__name__action_unequip_post"
										r.pathPattern = "/my/{name}/action/unequip"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

								elem = origElem
							}

							elem = origElem
						case 'l': // Prefix: "logs"
							origElem := elem
							if l := len("logs"); len(elem) >= l && elem[0:l] == "logs" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = "GetCharacterLogsMyNameLogsGet"
									r.summary = "Get Character Logs"
									r.operationID = "get_character_logs_my__name__logs_get"
									r.pathPattern = "/my/{name}/logs"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

							elem = origElem
						}

						elem = origElem
					}

					elem = origElem
				}

				elem = origElem
			case 'r': // Prefix: "resources/"
				origElem := elem
				if l := len("resources/"); len(elem) >= l && elem[0:l] == "resources/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = "GetAllResourcesResourcesGet"
						r.summary = "Get All Resources"
						r.operationID = "get_all_resources_resources__get"
						r.pathPattern = "/resources/"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				// Param: "code"
				// Leaf parameter
				args[0] = elem
				elem = ""

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = "GetResourcesResourcesCodeGet"
						r.summary = "Get Resources"
						r.operationID = "get_resources_resources__code__get"
						r.pathPattern = "/resources/{code}"
						r.args = args
						r.count = 1
						return r, true
					default:
						return
					}
				}

				elem = origElem
			case 't': // Prefix: "token/"
				origElem := elem
				if l := len("token/"); len(elem) >= l && elem[0:l] == "token/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "POST":
						r.name = "GenerateTokenTokenPost"
						r.summary = "Generate Token"
						r.operationID = "generate_token_token__post"
						r.pathPattern = "/token/"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

				elem = origElem
			}

			elem = origElem
		}
	}
	return r, false
}
